config/routes.rb
Rails.application.routes.draw do
 
  get 'users/show'
  resources :prints do
    resources :comments
    member do 
  		put 'like', to: "prints#like"
  		put 'unlike', to: "prints#unlike"
  	end
  end
  
  match '/users/:id', to: 'users#show', via: 'get' 
  devise_for :users, controllers: { registrations: 'registrations'}, :path_prefix => 'd'
  resources :users, :only =>[:show]
  root 'prints#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :print
    belongs_to :user
end

app/models/print.rb
class Print < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    mount_uploader :user_print, UserPrintUploader
    is_impressionable
    acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :prints, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @print = Print.find(params[:print_id]) 
  	@comment = @print.comments.create(comment_params)  
  	@comment.user_id = current_user.id if current_user 
  	@comment.save!

  	redirect_to print_path(@print)
  end

  def destroy
    @print = Print.find(params[:print_id])
  	@comment = @print.comments.find(params[:id])
  	@comment.destroy
  	redirect_to print_path(@print)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :response)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  before_action :set_print, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :like, :unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  # GET /prints or /prints.json
  def index
    @prints = Print.all.order('created_at DESC')
  end

  # GET /prints/1 or /prints/1.json
  def show
    
  end

  # GET /prints/new
  def new
    @print = current_user.prints.build
  end

  # GET /prints/1/edit
  def edit
  end

  # POST /prints or /prints.json
  def create
    @print = current_user.prints.build(print_params)

    respond_to do |format|
      if @print.save
        format.html { redirect_to @print, notice: "Print was successfully created." }
        format.json { render :show, status: :created, location: @print }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prints/1 or /prints/1.json
  def update
    respond_to do |format|
      if @print.update(print_params)
        format.html { redirect_to @print, notice: "Print was successfully updated." }
        format.json { render :show, status: :ok, location: @print }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    @print.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  def unlike
    @print.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render layout:false }
    end
  end

  # DELETE /prints/1 or /prints/1.json
  def destroy
    @print.destroy
    respond_to do |format|
      format.html { redirect_to prints_url, notice: "Print was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_print
      @print = Print.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def print_params
      params.require(:print).permit(:title, :description, :user_print)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
   
     def sign_up_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
     end
   
     def account_update_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
     end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    @prints = @user.prints.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def verbose_date(date)
		date.strftime('%B %d %Y')
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.email.gsub('spam', 'mdeering'), alt: comment.user.name, 
        gravatar: { size: 48 }) %>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong>
          <div><%= comment.response %></div>
        </p>
      </div>
    </div>
    <% if (user_signed_in? && (current_user.id == comment.user_id)) %>
       <%= link_to 'Delete', [comment.print, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@print, @print.comments.build]) do |f| %>

	<div class="field">
		<div class="control">
			<%= f.input :name, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>

	<div class="field">
		<div class="control">
			<%= f.input :response, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
		</div>
	</div>
	
	<%= f.button :submit, 'Leave a reply', class: 'button is-primary' %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Canvas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    	<div class="notification is-primary global-notification">
  	  	<p class="notice"><%= notice %></p>
    	</div>
   	<% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5 has-text-white">Canvas</h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id="navbar" class="navbar-menu">
        <div class="navbar-start">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Prints', root_path , class:"button is-dark" %>
              </p>
            </div>
          </div>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
              <p class="control">
                <%= link_to new_print_path, class:"button is-primary"  do %>
                  <span class="icon is-small"><i class="fa fa-upload"></i></span>
                  <span>New Print</span>
                <% end %>
              </p>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link"><%= current_user.name %></a>
                <div class="navbar-dropdown">
                  <p class="control">
                    <%= link_to 'Profile', current_user, class: "navbar-item" %>
                  </p>
                  <p class="control">
                        <%= link_to 'Edit profile', edit_user_registration_path, class: "navbar-item" %>
                  </p>
                </div>
              </div>
              <p class="control">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"button is-dark" %>
              </p>
              <% else %>
              <p class="control">
                 <%= link_to "Sign In", new_user_session_path, class:"button is-dark" %>
              </p>
              <p class="control">
                <%= link_to "Sign up", new_user_registration_path, class:"button is-dark"%>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav> 

    <%= yield %>
  </body>
</html>

app/views/prints/_form.html.erb
<%= simple_form_for @print, html: { multipart: true }  do |f| %>
  <%= f.error_notification %>
  <div class="columns is-centered">
    <div class="column is-half">
    
    <% unless @print.user_print.blank? %>
    <%= image_tag (@print.user_print_url), id: "previewImage" %>
    <% end %>

    <output id="list"></output>
    <div id="drop_zone">Drag your print here</div>
    <br />

    <%= f.input :user_print, label: false, input_html: { class: "file-input", type: "file" }, wrapper: false,
                 label_html: { class: "file-label" } %>

    <div class="field">
      <div class="control">
        <%= f.input :title, label: "Title", input_html: { class: "input"}, wrapper: false, 
                     label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
    	<div class="control">
        <%= f.input :description, input_html: { class: "textarea"}, wrapper: false, 
                     label_html: { class: "label" } %>
      </div>
    </div>

    <div class="field">
    	<div class="control">
      	<%= f.button :submit, class:"button is-primary" %>
      </div>
    </div>
  </div>
</div>

 
<% end %>

app/views/prints/_hero.html.erb
<% if !user_signed_in? %>
	<section class="hero is-dark">
		<div class="hero-body">
			<div class="container has-text-centered">
				<h1 class="title is-size-5">
					What are you working on? 
                    <span class="has-text-grey-light">Canvas is where designers get inspired.</span>
				</h1>
				<div class="content">
					<%= link_to "Login", new_user_session_path, class: "button is-primary" %>
				</div>
			</div>
		</div>
	</section>
<% end %>

app/views/prints/edit.html.erb
<section class="section">
	<div class="container">
		<h1 class="title has-text-centered">Editing Print</h1>
		<%= render 'form', print: @print %>
	</div>
</section>

app/views/prints/index.html.erb
<%= render 'hero' %>

<section class="section">
  <div class="prints">
    <% @prints.each do |print| %>
      <div class="print-grid-item">
        <div class="print-wrapper">  

          <%= link_to print, class: "print" do %>
            <%= image_tag(print.user_print_url) %>
            <div class="print-data">
              <h3 class="print-title"><%= print.title %></h3>
              <div class="print-description"><%= truncate(print.description, length: 60) %></div>
              <div class="print-time">
                <%= time_ago_in_words(print.created_at) %>
              </div>
            </div>
          <% end %>

          <nav class="level print-analytics">
            <div class="level-left"></div>
              <div class="level-right">
                <div class="level-item views data">
                  <%= link_to print do %>
                    <span class="icon"><i class="fa fa-eye"></i></span>
                    <%= print.impressionist_count %>
                  <% end %>
                </div>
                <div class="level-item comments data">
                  <%= link_to print do %>
                    <span class="icon"><i class="fa fa-comment"></i></span>
                    <%= print.comments.count %>
                  <% end %>
                </div>
                <div class="level-item likes">
                <% if user_signed_in? %>                
                  <% if current_user.liked? print %>
                    <%= link_to unlike_print_path(print), method: :put, class: "unlike_print" do %>
                      <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                      <span class="vote_count"><%= print.get_likes.size %></span>
                    <% end %>
                  <% else %>
                    <%= link_to like_print_path(print), method: :put, class: "like_print" do %>
                      <span class="icon"><i class="fa fa-heart"></i></span>
                      <span class="vote_count"><%= print.get_likes.size %></span>
                    <% end %>
                  <% end %>
                <% else %>
                  <%= link_to like_print_path(print), method: :put, class: "like_print" do %>
                    <span class="icon"><i class="fa fa-heart"></i></span>
                    <span class="vote_count"><%= print.get_likes.size %></span>
                  <% end %>
              <% end %>
                </div>
            </div>
          </nav>
        </div>
        <div class="user-data">
          <div class="user-thumb">
            <%= gravatar_image_tag(print.user.email.gsub('spam', 'mdeering'), alt: print.user.name, gravatar: { size: 20 }); %>
          </div>
          <div class="user-name"><%= print.user.name %></div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/prints/new.html.erb
<%= javascript_pack_tag 'prints.js' %>
<section class="section">
	<div class="container">
		<h1 class="title is-2 has-text-centered">What are you working on?</h1>
		<%= render 'form', print: @print %>
	</div>
</section>

app/views/prints/show.html.erb
<div class="section">
	<div class="container">
		<h1 class="title is-3"><%= @print.title %></h1>
		<div class="columns">
			<div class="column is-8">
				<span class="by has-text-grey-light">by</span>
				<div class="user-thumb">
          			<%= gravatar_image_tag(@print.user.email.gsub('spam', 'mdeering'), alt: @print.user.name, 
                                 gravatar: { size: 20 }); %>
				</div>
				<div class="user-name has-text-weight-bold"><%= @print.user.name %></div>
				<div class="print-time"><span class="has-text-grey-light">posted</span>
        		<span class="has-text-weight-semibold">
					<%= verbose_date(@print.created_at) %>
				</span></div>
			</div>	
		</div>

		<div class="columns">
			<div class="column is-8">
				<div class="print-container">
					<div class="print-full">
						 <%= image_tag @print.user_print_url unless @print.user_print.blank? %>
					</div>

					<% if user_signed_in? && (current_user.id == @print.user_id) %>		
						<div class="buttons has-addons">
							<%= link_to 'Edit', edit_print_path(@print), class: "button" %>
              				<%= link_to 'Delete', print_path, class: "button", method: :delete, 
                  								data: { confirm: 'Are you sure you want to delete this print?'} %>
						</div>
					<% end %>

					<div class="content">
						<%= @print.description %>
					</div>

					<section class="comments">
						<h2 class="subtitle is-5"><%= pluralize(@print.comments.count, 'Comment') %></h2>
						<%= render @print.comments %>							
						<hr />
						<% if user_signed_in? %>
							<div class="comment-form">
								<h3 class="subtitle is-3">Leave a reply</h3>
								<%= render 'comments/form' %>								
							</div>
						<% else %>
							<div class="content"><%= link_to 'Sign in', new_user_session_path %> to leave a comment.</div>
						<% end %>
					</section>

				</div>
			</div>
			<div class="column is-3 is-offset-1">
				<div class="nav panel show-print-analytics">
					<div class="panel-block views data">
						<span class="icon"><i class="fa fa-eye"></i></span>
						<%= pluralize(@print.impressionist_count, 'View')%>
					</div>
					<div class="panel-block comments data">
						<span class="icon"><i class="fa fa-comment"></i></span>
						<%= pluralize(@print.comments.count, 'Comment')%>
					</div>
					<div class="panel-block likes data">					
						<% if user_signed_in? %>
							<% if current_user.liked? @print %>
								<%= link_to unlike_print_path(@print), method: :put, class: "unlike_print" do %>
									<span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
									<span class="vote_count"><%= pluralize(@print.get_likes.size, 'Like') %></span>
								<% end %>
						    <% else %>
								<%= link_to like_print_path(@print), method: :put, class: "like_print" do %>
									<span class="icon"><i class="fa fa-heart"></i></span>
									<span class="vote_count"><%= pluralize(@print.get_likes.size, 'Like') %></span>
								<% end %>
              				<% end %>
            			<% else %>
							<%= link_to like_print_path(@print), method: :put, class: "like_print" do %>
								<span class="icon"><i class="fa fa-heart"></i></span>
								<span class="vote_count"><%= pluralize(@print.get_likes.size, 'Like') %></span>
							<% end %>
            			<% end %>                
              
              
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="user-thumb-profile">
                <%= gravatar_image_tag(@user.email.gsub('spam', 'mdeering'), alt: @user.name, 
                                        gravatar: { size: 80 }); %>
            </div>
            <h1 class="title is-3"><%= @user.name %></h1>
        </div>        
        <hr />

        <div class="prints">
            <% @prints.each do |print| %>
                <div class="print-grid-item">
                    <div class="print-wrapper">
                        <%= link_to print, class: "print" do %>
                            <%= image_tag(print.user_print_url) %>
                            <div class="print-data">
                                <h3 class="print-title"><%= print.title %></h3>
                                <div class="print-description"><%= truncate(print.description, length: 60) %></div>
                                <div class="print-time">
                                    <%= time_ago_in_words(print.created_at) %>
                                </div>
                            </div>
                        <% end %>
                        <nav class="level print-analytics">
                            <div class="level-left"></div>
                            <div class="level-right">
                                <div class="level-item views data">
                                    <%= link_to print do %>
                                        <span class="icon"><i class="fa fa-eye"></i></span>
                                        <%= print.impressionist_count %>
                                    <% end %>
                                </div>
                                <div class="level-item comments data">
                                    <%= link_to print do %>
                                        <span class="icon"><i class="fa fa-comment"></i></span>
                                        <%= print.comments.count %>
                                    <% end %>
                                </div>
                        <div class="level-item likes">                                    
                            <% if current_user.liked? print %>
                                <%= link_to unlike_print_path(print), method: :put, class: "unlike_print" do %>
                                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                                    <span class="vote_count"><%= print.get_likes.size %></span>
                                <% end %>
                            <% else %>
                                <%= link_to like_print_path(print), method: :put, class: "like_print" do %>
                                    <span class="icon"><i class="fa fa-heart"></i></span>
                                    <span class="vote_count"><%= print.get_likes.size %></span>
                                <% end %>
                            <% end %>                        
                        </div>
                    </div>
                </nav>
                </div>        
            </div>
            <% end %>
        </div>
            
       
    </div>
</div>